In [77]:
import numpy as np

In [78]:
X = [
    [1,0,1,1],
    [1,0,0,1],
    [1,1,1,0],
    [0,1,1,0],
]
Y  = [1,0,0,1]

In [79]:
x = np.array(X)
y = np.array(Y)

In [80]:
print("x :","\n",x,"\n",x.shape)
print("\n")
print("y :","\n",y,"\n",y.shape)


x : 
 [[1 0 1 1]
 [1 0 0 1]
 [1 1 1 0]
 [0 1 1 0]] 
 (4, 4)


y : 
 [1 0 0 1] 
 (4,)


In [88]:
class Sequential():
    
    def __init__(self,*args,**kwargs):
        self.layers = args[0]
        self.name = kwargs.get('name',"Model")
        self.learning_rate = 0.001
    
    def summary(self):
        print(self.name)
        for _ in self.layers:
            print(_.name,_.units)
    
    def compile(self):
        pass
    
    def fit(self,x,y,epochs=1):   
        m = x.shape[0]
        n = x.shape[1]
        output = list()
        #layers forward pass
        act = x 
        loss = list()
        for i in range(epochs):
            for layer in self.layers:
                act = layer.forward(x=act)
            
            # losses = compute_losses()
            # cost = compute_cost()
            # #backward pass
            # for layer in self.layers:
            #     layer.backward(learning_rate=learning_rate,losses)
        
        return act
            
            

In [89]:
class Dense():
    
    def __init__(self,units:int=1,name:str="dense",activation:str="relu"):
        self.name = name
        self.activation = activation
        self.units = units
        self.x = None
        self.w = None
        self.b = None
        
    def forward(self,x,w=None,b=None):
        
        w = np.random.uniform(low=0.0, high=1.0, size=(x.shape[1],self.units))
        b = np.random.uniform(size=(1,self.units))
        act = self.activation
        activation_func = self.get_acts(act)
        z = np.matmul(x,w) + b
        g = activation_func(z)
        return g
        
    @staticmethod    
    def loss(yhat,yactual):
        loss = yhat - yactual
        return loss
    
    def gradient_desc():
        pass
    
    def backward():
        pass
    
    @staticmethod
    def sigmoid(x):
        exp_term = 1 + np.exp(-x)
        return 1/exp_term
    
    @staticmethod
    def relu(x):
        return np.maximum(x, 0)
    
    
    def get_acts(self,name='relu'):
        if name == 'sigmoid':
            return self.sigmoid
        
        if name == 'relu':
            return self.relu
        
    

In [90]:
class Input():
    
    def __init__(self,shape):
        self.shape = shape
        self.act = None
        self.name = "Input_layer"
        self.units = shape[0]
    
    def forward(self,x,*args,**kwargs):
        return x
    
    def backward(self,*args,**kwargs):
        pass
    
    def __str__(self):
        return f"{(self.name,self.shape)}"
        
    

In [91]:
model = Sequential([
                        Input(shape=(32,32)),
                        Dense(units=128,activation="sigmoid",name="dense_1"),
                        Dense(units=50,name="dense_2"),
                        Dense(units=10,name="dense_3"),
                        Dense(units=2,name="dense_4")
                        
],name="my_model")

In [92]:
model.summary()

my_model
Input_layer 32
dense_1 128
dense_2 50
dense_3 10
dense_4 2


In [93]:
model.fit(x,y)

array([[5651.65286474, 5224.33827818],
       [5226.37678292, 4830.96946468],
       [5682.93841935, 5253.44548727],
       [5308.8501059 , 4907.95297482]])